### PR TITLE
PvaClient::get if providerName not ca or pva check ChannelProviderRegistry

### PR DESCRIPTION
**Pull request by mrkraimer**
Title explains change

### CODE REVIEW

**Comment by ralphlange** [comment]
Don't know if I had mentioned it:
Please do _not_ merge the target branch unless you have conflicts that keep the CloudBees PR builder from test-building.

**Comment by mrkraimer** [comment]
On 04/20/2016 01:00 PM, Ralph Lange wrote:

> Don't know if I had mentioned it:
> Please do /not/ merge the target branch unless you have conflicts that 
> keep the CloudBees PR builder from test-building.

If I see my target branch is more than one  commit behind epics-base 
then I pull from epics-base BEFORE
1) pushing
2)  issuing a merge request in epics-base

What is wrong with following this procedure?

**Comment by ralphlange** [comment]
It is not required and creates unnecessary merge commits, making it harder to review.

The CloudBees PR build job already does that merge when test-building the PR. If the merge has conflicts or does not build, the PR build jobs fails, and you will be notified.
Only in that case it makes sense to merge the target back to the PR to resolve the issue.

**Comment by ralphlange** [comment]
If you insist on locally test-building the merge result (e.g. because you don't trust the CloudBees job or want to test-build for a different target)
- clone the target branch into a temporary test-branch
- merge the PR candidate into the test-branch
- build and test the test-branch
- throw away the test-branch

This allows you to do anything, without leaving traces.
(BTW: this is exactly what the CloudBees PR builder job does.)

**Comment by mrkraimer** [comment]
On 04/21/2016 05:35 AM, Ralph Lange wrote:

> If you insist on locally test-building the merge result (e.g. because 
> you don't trust the CloudBees job or want to test-build for a 
> different target)
> - clone the target branch into a temporary test-branch
> - merge the PR candidate into the test-branch
> - build and test the test-branch
> - throw away the test-branch
> 
> This allows you to do anything, without leaving traces.
> (BTW: this is exactly what the CloudBees PR builder job does.)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/epics-base/pvaClientJava/pull/11#issuecomment-212830879

I do not understand why I have to do this.

I am at
mrk> cat .git/config
[core]
     repositoryformatversion = 0
     filemode = true
     bare = false
     logallrefupdates = true
[remote "origin"]
     url = https://github.com/mrkraimer/pvaClientJava
     fetch = +refs/heads/_:refs/remotes/origin/_
[branch "master"]
     remote = origin
     merge = refs/heads/master

When I look at the git documentation about working collaboratively, it 
talks about things like

git remote add upstream https://github.com/epics-base/pvaClientJava
git fetch upstream
git merge upstream/master

Is this OK to do?

But this looks to me just  like saying

git pull https://github.com/epics-base/pvaClientJava

Am I wrong?

**Comment by anjohnson** [comment]
Marty, every time you merge changes from the master branch into your development branch, you are actually doing a commit to your branch, which will appear in your git log. As long as there are no conflicts the `git pull` command automatically creates this commit behind the scenes and gives it a standard log message. When your branch later gets merged into the master branch though, that commit will appear in the history from your branch that was merged into master, but there will be no file changes associated with it on the master branch (because all those changes had already been merged into master earlier on).

Looking through the [commit history of this module](https://github.com/epics-base/pvaClientJava/commits/master) I can see a couple of these:
- 812ab28702a47e40d471d0f2fb0bf4433987fb5f
- 77da43bcc086a4fad0cac2ab0c9a594ab52325a8

If you read this comment on the github site it converts those two SHA hashes into links which you can click to see that they are indeed empty.

Ralph is asking you to _not_ merge the changes from master at all, so neither `git pull` nor the `git fetch`/`git merge` thing so we don't get the empty commits; just let github's pull request mechanisms check for you whether your work will conflict with any other changes that have been merged since you started working. I agree that this is contrary to what we had to do with CVS (we always had to do an update before we could commit) but this is one of those things that git just does differently.

If the github checks point out that there is a conflict between your branch and the master (or if you know in advance for certain that there will be one), then it is OK to do the `git pull`, fix the merge conflict by hand, commit your fix and push the result back to github.

Alternatively you could also try using `git pull --rebase` which will rewrite your local commits as though the master changes had happened before you even started work. However as the note in the `git help pull` text says, this is a potentially dangerous thing to do since you can lose commits if you're not careful, but as long as you haven't pushed before doing the rebase it should be relatively safe.

HTH,
- Andrew

**Comment by mrkraimer** [comment]
On 04/21/2016 02:22 PM, Andrew Johnson wrote:

> Marty, every time you merge changes from the master branch into your 
> development branch, you are actually doing a commit to your branch, 
> which will appear in your git log. As long as there are no conflicts 
> the |git pull| command automatically creates this commit behind the 
> scenes and gives it a standard log message. When your branch later 
> gets merged into the master branch though, that commit will appear in 
> the history from your branch that was merged into master, but there 
> will be no file changes associated with it on the master branch 
> (because all those changes had already been merged into master earlier 
> on).
> 
> Looking through the commit history of this module 
> https://github.com/epics-base/pvaClientJava/commits/master I can see 
> a couple of these:
> - 812ab28
>   https://github.com/epics-base/pvaClientJava/commit/812ab28702a47e40d471d0f2fb0bf4433987fb5f
> - 77da43b
>   https://github.com/epics-base/pvaClientJava/commit/77da43bcc086a4fad0cac2ab0c9a594ab52325a8
> 
> If you read this comment on the github site it converts those two SHA 
> hashes into links which you can click to see that they are indeed empty.
> 
> Ralph is asking you to /not/ merge the changes from master at all, so 
> neither |git pull| nor the |git fetch|/|git merge| thing so we don't 
> get the empty commits; just let github's pull request mechanisms check 
> for you whether your work will conflict with any other changes that 
> have been merged since you started working. I agree that this is 
> contrary to what we had to do with CVS (we always had to do an update 
> before we could commit) but this is one of those things that git just 
> does differently.
> 
> If the github checks point out that there is a conflict between your 
> branch and the master (or if you know in advance for certain that 
> there will be one), then it is OK to do the |git pull|, fix the merge 
> conflict by hand, commit your fix and push the result back to github.
> 
> Alternatively you could also try using |git pull --rebase| which will 
> rewrite your local commits as though the master changes had happened 
> before you even started work. However as the note in the |git help 
> pull| text says, this is a potentially dangerous thing to do since you 
> can lose commits if you're not careful, but as long as you haven't 
> pushed before doing the rebase it should be relatively safe.
> 
> HTH,
> - Andrew
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/epics-base/pvaClientJava/pull/11#issuecomment-213048886

So how do I know when I should pull from epics-base?

When I am working on the master branch of all the modules for the next 
release I want to make sure I am in sync with all the other developers.

For modules I have cloned from epics-base there is no problem.
I just do a pull and never do a push.

BUT what do I do for modules I am developing?

Assume several others are also making changes to a module.
Before I create a pull request in epics-base I want to make sure 
everything works.
This includes not just that everything compiles and regression tests but 
any testing I do in other modules.
Thus I want to make sure I have all the changes other developers have 
merged  into epics-base.

So how do I know when to pull from epics-base into mrkraimer?

Recently I had this problem in  pvAccessCPP for the src/ioc changes.
There had been several merges to epics-base after I started the src/ioc 
changes.
I wanted all these changes so I did a pull from epics-base into mrkraimer.

Most of the testing was not in pvAccessCPP but in exampleCPP.

So without doing a pull from epics-base for pvAccessCPP what should I 
have done?

Maybe --rebase is the answer?

Marty

**Comment by anjohnson** [comment]
Here's where Ralph's instructions come in; you check out (`git clone`) a second 'test' copy of the upstream master branch, and then merge the changes from your development branch into that test tree (which is exactly what github does). If there are no conflicts from that merge you can build and test that tree to make sure the code still works with your changes added. You don't need the test tree after you've finished that checking so it's probably best to delete it in order to avoid any future confusion (it will have be a merge commit in its history which won't ever appear on the master branch, so don't try to re-use it).

If you do get conflicts from the test merge you now know that cloudbees builder will have the same problem, so in this case you _should_ `git pull` the master branch into your development tree and manually resolve the conflicts and commit/push the merge before creating the pull request.
- Andrew

**Comment by gregoryraymondwhite** [comment]
And don’t forget to solve the the Arab-Israeli conflict on the way.

Andrew, Would you give an example in the cheatsheet I started? 
Thanks, greg

pvDataWWW/mainPage/cheatsheet.txt

http://epics-pvdata.sourceforge.net/cheatsheet.txt

**Comment by mrkraimer** [comment]
On 04/21/2016 05:40 PM, Andrew Johnson wrote:

> Here's where Ralph's instructions come in; you check out (|git clone|) 
> a second 'test' copy of the upstream master branch, and then merge the 
> changes from your development branch into that test tree (which is 
> exactly what github does). If there are no conflicts from that merge 
> you can build and test that tree to make sure the code still works 
> with your changes added. You don't need the test tree after you've 
> finished that checking so it's probably best to delete it in order to 
> avoid any future confusion (it will have be a merge commit in its 
> history which won't ever appear on the master branch, so don't try to 
> re-use it).

So the final result is that the test copy now is up to data with 
epics-base but my working version is not.
But my goal was to have my working version up to date with epics-base.

> If you do get conflicts from the test merge you now know that 
> cloudbees builder will have the same problem, so in this case you 
> /should/ |git pull| the master branch into your development tree and 
> manually resolve the conflicts and commit/push the merge before 
> creating the pull request.
> - Andrew
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/epics-base/pvaClientJava/pull/11#issuecomment-213123871

I think the problem is that the goal for epics-base is in conflict with 
the goal for the developer (in my case mrkraimer).

The goal for epics-base is to have a clean set of merges so that it is 
easy to look at changes between commits.

For mrkraimer my goal is to have my modules up to date with other merges 
to epics-base when I am doing final testing before I make a pull request 
to epics-base.
Again use the example of a change I make to pvAccessCPP but testing is 
mostly done in exampleCPP.

Here is a technique that I think should satisfy both goals.

mrk> pwd
/home/epicsv4/master
git clone https://github.com/mrkraimer/pvAccessCPP.git pvAccessCPPMRK
cd pvAccessCPPMRK
git pull --rebase https://github.com/epics-base/pvAccessCPP.git
git push

Now when I look on github
https://github.com/mrkraimer/pvAccessCPP
and
https://github.com/epics-base/pvAccessCPP
both show the same number of commits.

Thus it looks like I am completely in sync with epics-base

I did this in a freshly cloned directory so that if the  pull request 
shows problems I can follow a different strategy.
But if no problem occur than I can:
mrk> cd ..
mrk> pwd
/home/epicsv4/master
mrk> cp -a pvAccessCPP pvAccessCPPTEMP  - This is just in case the next 
step fails
mrk> cd pvAccessCPP -NOTE this is mrkraimer NOT epics-base
mrk> git pull
Then I can do my testing and then commit and push my changes and then 
create a pull request in epics-base.
There could be a problem if my new changes conflict with changes others 
made.
But this is my problem to resolve and pvAccessCPPTEMP does have the 
latest working version of mrkraimer.

**Comment by anjohnson** [comment]
Rebasing is great as long as you are the only person working on this branch. As soon as someone else gets a copy of your git branch history though (for example if you push it to github and they clone it from there) you have to be very careful when you rebase. If they want you to merge some of their own modifications into your branch you _cannot_ rebase between the time they check out the branch and your merging their changes into it, because a rebased commit has a completely different SHA than it did before. After a rebase you are effectively working on a totally new branch that git will think is not the same as or even compatible with the old one, so it will get very confused if you try to merge the results. If you get stuck in that situation, you might have to resort to applying patch files by hand.

You may also find that you have to use the `--force` flag to `git push` if you have pushed your unrebased changes and they want to push the rebased version to the same place. Git thinks you are throwing away the pre-rebasing commits when you do that, so it makes you use `--force`.

**Comment by mrkraimer** [comment]
On 04/22/2016 01:35 PM, Andrew Johnson wrote:

> Rebasing is great as long as you are the only person working on this 
> branch. As soon as someone else gets a copy of your git branch history 
> though (for example if you push it to github and they clone it from 
> there) you have to be very careful when you rebase. If they want you 
> to merge some of their own modifications into your branch you /cannot/ 
> rebase between the time they check out the branch and your merging 
> their changes into it, because a rebased commit has a completely 
> different SHA than it did before. After a rebase you are effectively 
> working on a totally new branch that git will think is not the same as 
> or even compatible with the old one, so it will get very confused if 
> you try to merge the results. If you get stuck in that situation, you 
> might have to resort to applying patch files by hand.

But I am the only one working on
https://github.com/mrkraimer/pvaClientJava

When I do a
git pull --rebase https://github.com/epics-base/ 
https://github.com/epics-base/pvAccessCPP.gitpvaClientJava

All I am doing is getting the commits in mrkraimer in sync with the 
commits in epics-base.
No one else is pulling from or pushing to 
https://github.com/mrkraimer/pvaClientJava.

An once more let me state my goal:

I want https://github.com/mrkraimer/pvaClientJava to have the latest 
commits to https://github.com/epics-base/pvaClientJava.
I want this for my final testing before I push changes to mrkraimer and 
then issue a pull request in epics-base.
AND again most of the testing is in exampleJava NOT pvaClientJava.
Thus I need all the commits that have been done to epics-base.

Marty

**Pull request merged**
